
cfg: &cfg
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  username: root
  password: root
  socket: /var/run/mysqld/mysqld.sock


development:
  <<: *cfg
  database: mycode_development

test:
  <<: *cfg
  database: mycode_test

production:
  <<: *cfg
  database: mycode_production
